<?xml version="1.0"?>

<robot name="rov" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="namespace" default="rov"/>
  <xacro:arg name="visualize" default="true"/>
    <!-- Necessary for sensors -->
    <xacro:include filename="$(find deep_ocean)/urdf_xacro_files/sensors_and_actuators/sonar_snippets.xacro" />
    <xacro:include filename="$(find deep_ocean)/urdf_xacro_files/sensors_and_actuators/sensor_snippets.xacro" />
    <!-- <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/> -->
    <!-- Necessary for thrusters -->
    <xacro:include filename="$(find deep_ocean)/urdf_xacro_files/sensors_and_actuators/actuators.xacro" />
    <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro" />
    <xacro:include filename="$(find deep_ocean)/urdf_xacro_files/sensors_and_actuators/thruster_snippets.xacro" />
    <!-- Necessary for state publishing -->
    <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/misc.xacro" />

    <!-- Fluid Density of Water (kg/mÂ³) -->
    <xacro:property name="fluid_density" value="1028"/>

    <!-- Hardcoded Dimensions from the Collision Mesh -->
    <xacro:property name="size_y" value="0.833"/> <!-- Width -->
    <xacro:property name="size_x" value="1.25"/>  <!-- Length -->
    <xacro:property name="size_z" value="0.77"/>  <!-- Height -->

    <!-- Mass of the ROV -->
    <xacro:property name="mass" value="326"/>

    <!-- Compute Volume to Ensure Neutral Buoyancy -->
    <xacro:property name="volume" value="${mass / fluid_density}"/>

    <!-- Center of Buoyancy Adjusted -->
    <xacro:property name="cob_z" value="${0.5 * size_z}"/>

    <!-- Inertia Calculation -->
    <xacro:property name="ixx" value="${(1/12) * mass * (size_x * size_x + size_z * size_z)}"/>
    <xacro:property name="iyy" value="${(1/12) * mass * (size_y * size_y + size_z * size_z)}"/>
    <xacro:property name="izz" value="${(1/12) * mass * (size_y * size_y + size_x * size_x)}"/>

    <!-- Define Base Link -->
    <link name="$(arg namespace)/base_link">
        <inertial>
            <mass value="${mass}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${ixx}" ixy="0.0" ixz="0.0" iyy="${iyy}" iyz="0.0" izz="${izz}"/>
        </inertial>

        <!-- Visual Representation -->
        <visual>
            <geometry>
                <mesh filename="package://deep_ocean/meshes/rov_visual.dae" scale="1 1 1"/>
            </geometry>
        </visual>

        <!-- Collision Geometry -->
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://deep_ocean/meshes/rov_collision.stl" scale="1 1 1"/>
            </geometry>
        </collision>
    </link>

    <!-- Initiating thrusters from UUV -->
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="0">
    <origin xyz="0.56374 0.22357 0.38038" rpy="1.5708 0 ${-0.6981}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="1">
    <origin xyz="-0.15606 0.3381 0.38038" rpy="1.5708 0 ${0.6981}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="2">
    <origin xyz="-0.060821 0.30171 0.70723" rpy="0.1745 ${-0.3491-pi/2} ${pi/2}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="3">
    <origin xyz="0.56374 -0.22357 0.38038" rpy="1.5708 0 ${0.6981}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="4">
    <origin xyz="-0.060821 -0.3017 0.70723" rpy="0.1745 ${0.3491-pi/2} ${pi/2}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="5">
    <origin xyz="-0.15606 -0.3381 0.38038" rpy="1.5708 0 ${-0.6981}"/>
  </xacro:thruster_macro>
  <xacro:thruster_macro namespace="$(arg namespace)" thruster_id="6">
    <origin xyz="0.39991 -0.002266 0.70723" rpy="-0.3491 ${-pi/2} ${pi/2}"/>
  </xacro:thruster_macro>

  <xacro:default_joint_state_publisher namespace="$(arg namespace)" update_rate="50"/>

    <!-- initilizing Sonar macro -->
  <xacro:forward_multibeam_sonar_m450_130 namespace="$(arg namespace)" parent_link="$(arg namespace)/base_link" visualize="$(arg visualize)">
    <origin xyz="0.63 0 0.63" rpy="0 0 0"/>
  </xacro:forward_multibeam_sonar_m450_130>

    <!-- mounting camera -->
  <!--xacro:default_camera namespace="$(arg namespace)" parent_link="$(arg namespace)/base_link" suffix="">
    <origin xyz="0.63 0 0.4" rpy="0 0.6 0"/>
  </xacro:default_camera-->

    <gazebo>
        <plugin name="uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
            <fluid_density>${fluid_density}</fluid_density>
            <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
            <debug>0</debug>      
            <link name="$(arg namespace)/base_link">
                <neutrally_buoyant>1</neutrally_buoyant>  <!-- Ensures mass and volume decide float/sink -->
                <volume>${volume}</volume>  
                <box>
                    <width>${size_y}</width>
                    <length>${size_x}</length>
                    <height>${size_z}</height>
                </box>
                <center_of_buoyancy>0 0 ${cob_z}</center_of_buoyancy>

                <!-- Hydrodynamic Model using Fossen type -->
                <hydrodynamic_model>
                    <type>fossen</type>

                    <!-- Rough Added Mass Estimation -->
                    <added_mass>
                        ${0.1 * mass}  0  0  0  0  0
                        0  ${0.1 * mass}  0  0  0  0  
                        0  0  ${0.1 * mass}  0  0  0
                        0  0  0  ${0.05 * mass}  0  0
                        0  0  0  0  ${0.05 * mass}  0
                        0  0  0  0  0  ${0.05 * mass}
                    </added_mass>

                    <!-- Rough Linear Damping Estimation -->
                    <linear_damping>
                        ${-100 * size_y} ${-100 * size_x} ${-100 * size_z} 
                        ${-40 * size_z} ${-40 * size_x} ${-40 * size_y}
                    </linear_damping>

                    <!-- Rough Quadratic Damping Estimation -->
                    <quadratic_damping>
                        ${-120 * size_y} ${-120 * size_x} ${-120 * size_z} 
                        ${-50 * size_z} ${-50 * size_x} ${-50 * size_y}
                    </quadratic_damping>

                </hydrodynamic_model>

            </link>    
        </plugin>
    </gazebo>  

    <!-- imu sensor -->
    <xacro:imu_sensor parent_link="$(arg namespace)/base_link" namespace="$(arg namespace)">
        <origin xyz="0 0 0.63" rpy="0 0 0"/>
    </xacro:imu_sensor>

      <!-- camera -->
    <xacro:camera_sensor parent_link="$(arg namespace)/base_link" namespace="$(arg namespace)">
    <origin xyz="0.63 0 0.4" rpy="0 0 0"/>
    </xacro:camera_sensor>

</robot>
